/* eslint-env node */

module.exports = {
  version: "0.1",
  language: "en",
  words: [
    "Akko",
    "allowfullscreen",
    "allowtransparency",
    "autoplay",
    "autorun",
    "blockly",
    "canplay",
    "crossorigin",
    "Emittery",
    "fittoscreen",
    "fontscssurl",
    "fullscreen",
    "geogebra",
    "Geos",
    "isequal",
    "lazyload",
    "listcontents",
    "Magix",
    "mpegurl",
    "Multiuser",
    "Mutex",
    "Pagenum",
    "plyr",
    "pnpm",
    "Quan",
    "randomcolor",
    "submenu",
    "submenus",
    "Tele",
    "telebox",
    "tubeid",
    "ungroup",
    "unlisten",
    "userid",
    "Xcoord",
    "xscale",
    "Ycoord",
    "youtu",
    "yscale",
    "Zcoord",
    "zscale",
    "courseware",
    "vite",
    "NETLESSROOM",
  ],
  flagWords: ["fuck", "bitch", "asshole", "bullshit", "crap", "suck", "wtf"],
  dictionaries: [
    "softwareTerms",
    "typescript",
    "node",
    "html",
    "css",
    "bash",
    "fonts",
    "filetypes",
    "npm",
    "en_US",
  ],
  ignorePaths: [
    "**/coverage/**",
    "**/node_modules/**",
    "**/dist/**",
    "packages/flat-components/build/**",
    "packages/flat-components/storybook-static/**",
    "desktop/main-app/release/**",
    "desktop/main-app/static/**",
    "cspell.config.js",
    "pnpm-lock.yaml",
    "CHANGELOG.md",
  ],
};
