name: GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      VITE_APPID: ${{ secrets.VITE_APPID }}
      VITE_ROOM_UUID: ${{ secrets.VITE_ROOM_UUID }}
      VITE_ROOM_TOKEN: ${{ secrets.VITE_ROOM_TOKEN }}
      VITE_JUDGE0_KEY: ${{ secrets.VITE_JUDGE0_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: 11.1.1
          run_install: false
      - run: pnpm approve-builds core-js esbuild protobufjs yjs
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm build-all
      - run: pnpm -F playground build:ci
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/playground/dist
